package main

import (
	"strings"
	"sync"
)

// enToZh maps English icon keywords to Chinese translations.
// Multiple translations are space-separated for broader matching.
var enToZh = map[string]string{
	// Navigation & Direction
	"home":       "首页 主页",
	"arrow":      "箭头",
	"chevron":    "V形箭头",
	"up":         "上 向上",
	"down":       "下 向下",
	"left":       "左 向左",
	"right":      "右 向右",
	"back":       "返回 后退",
	"forward":    "前进",
	"menu":       "菜单",
	"more":       "更多",
	"navigate":   "导航",
	"navigation": "导航",
	"compass":    "指南针",
	"location":   "位置 定位",
	"map":        "地图",
	"pin":        "固定 定位 图钉",
	"marker":     "标记",
	"route":      "路线",
	"path":       "路径",
	"direction":  "方向",
	"pointer":    "指针",
	"cursor":     "光标",
	"target":     "目标 靶心",
	"crosshair":  "准星",

	// Actions - Basic
	"add":        "添加 新增",
	"plus":       "加 加号",
	"minus":      "减 减号",
	"remove":     "移除 删除",
	"delete":     "删除",
	"close":      "关闭",
	"cancel":     "取消",
	"check":      "勾选 确认 检查",
	"tick":       "勾号",
	"cross":      "叉号",
	"edit":       "编辑 修改",
	"create":     "创建",
	"new":        "新建",
	"save":       "保存",
	"open":       "打开",
	"copy":       "复制",
	"paste":      "粘贴",
	"cut":        "剪切",
	"undo":       "撤销",
	"redo":       "重做",
	"refresh":    "刷新",
	"reload":     "重新加载",
	"reset":      "重置",
	"clear":      "清除",
	"clean":      "清理",
	"update":     "更新",
	"upgrade":    "升级",
	"sync":       "同步",
	"scan":       "扫描",
	"search":     "搜索 查找",
	"find":       "查找",
	"filter":     "筛选 过滤",
	"sort":       "排序",
	"select":     "选择",
	"select-all": "全选",
	"deselect":   "取消选择",

	// Actions - Communication
	"send":      "发送",
	"share":     "分享",
	"download":  "下载",
	"upload":    "上传",
	"export":    "导出",
	"import":    "导入",
	"reply":     "回复",
	"submit":    "提交",
	"publish":   "发布",
	"approve":   "批准",
	"reject":    "拒绝",
	"accept":    "接受",
	"decline":   "拒绝",
	"confirm":   "确认",
	"deny":      "拒绝",
	"report":    "报告",
	"block":     "屏蔽",
	"mute":      "静音",
	"follow":    "关注",
	"subscribe": "订阅",

	// Objects - Documents
	"file":      "文件",
	"folder":    "文件夹 目录",
	"document":  "文档",
	"page":      "页面",
	"paper":     "纸张",
	"note":      "笔记 音符",
	"notebook":  "笔记本",
	"book":      "书",
	"journal":   "日志",
	"diary":     "日记",
	"clipboard": "剪贴板",
	"archive":   "归档",
	"trash":     "回收站",
	"envelope":  "信封",
	"stamp":     "邮票",
	"receipt":   "收据",
	"invoice":   "发票",
	"ticket":    "票 券",
	"coupon":    "优惠券",

	// Objects - Communication
	"mail":         "邮件 邮箱",
	"email":        "电子邮件",
	"phone":        "电话 手机",
	"call":         "通话 拨打",
	"message":      "消息 信息",
	"chat":         "聊天 对话",
	"comment":      "评论",
	"notification": "通知",
	"bell":         "铃铛 通知",
	"megaphone":    "喇叭 扩音器",
	"announcement": "公告",

	// Objects - Media
	"image":      "图片 图像",
	"photo":      "照片",
	"camera":     "相机 摄像头",
	"video":      "视频",
	"film":       "电影 胶片",
	"music":      "音乐",
	"audio":      "音频 声音",
	"microphone": "麦克风 话筒",
	"speaker":    "扬声器 喇叭",
	"headphones": "耳机",
	"radio":      "收音机",
	"tv":         "电视",
	"monitor":    "显示器 屏幕",
	"screen":     "屏幕",
	"projector":  "投影仪",
	"playlist":   "播放列表",

	// Objects - Time
	"clock":     "时钟",
	"time":      "时间",
	"calendar":  "日历 日期",
	"timer":     "计时器",
	"stopwatch": "秒表",
	"alarm":     "闹钟",
	"schedule":  "日程",
	"hourglass": "沙漏",
	"history":   "历史",
	"deadline":  "截止日期",

	// Objects - Security
	"lock":        "锁 锁定",
	"unlock":      "解锁",
	"key":         "钥匙 密钥",
	"shield":      "盾牌 安全",
	"security":    "安全",
	"password":    "密码",
	"fingerprint": "指纹",
	"eye":         "眼睛 查看",
	"eye-off":     "隐藏",
	"visible":     "可见",
	"hidden":      "隐藏",
	"privacy":     "隐私",
	"verified":    "认证 已验证",
	"certificate": "证书",

	// Objects - People
	"user":    "用户 人物",
	"person":  "人 个人",
	"people":  "人们 人群",
	"group":   "群组 团队",
	"contact": "联系人",
	"avatar":  "头像",
	"profile": "个人资料",
	"team":    "团队",
	"crowd":   "人群",
	"man":     "男人",
	"woman":   "女人",
	"boy":     "男孩",
	"girl":    "女孩",
	"baby":    "婴儿",
	"elderly": "老人",

	// Objects - Devices
	"computer":   "电脑",
	"desktop":    "桌面",
	"laptop":     "笔记本 电脑",
	"mobile":     "手机",
	"tablet":     "平板",
	"keyboard":   "键盘",
	"mouse":      "鼠标",
	"printer":    "打印机",
	"scanner":    "扫描仪",
	"battery":    "电池",
	"charger":    "充电器",
	"power":      "电源",
	"plug":       "插头",
	"usb":        "USB",
	"cable":      "线缆",
	"chip":       "芯片",
	"cpu":        "处理器",
	"hard-drive": "硬盘",
	"server":     "服务器",
	"database":   "数据库",

	// Objects - Network
	"wifi":      "无线网络",
	"bluetooth": "蓝牙",
	"signal":    "信号",
	"antenna":   "天线",
	"router":    "路由器",
	"network":   "网络",
	"cloud":     "云",
	"globe":     "地球仪",
	"world":     "世界",
	"internet":  "互联网",
	"link":      "链接",
	"chain":     "链条",
	"web":       "网页",
	"browser":   "浏览器",
	"code":      "代码 编程",
	"terminal":  "终端",
	"git":       "Git",
	"branch":    "分支",
	"merge":     "合并",
	"commit":    "提交",
	"pull":      "拉取",
	"push":      "推送",

	// Objects - Finance
	"money":      "金钱",
	"dollar":     "美元",
	"euro":       "欧元",
	"yen":        "日元",
	"pound":      "英镑",
	"coin":       "硬币",
	"wallet":     "钱包",
	"bank":       "银行",
	"credit":     "信用",
	"cart":       "购物车",
	"shop":       "商店",
	"store":      "商店",
	"bag":        "袋子 包",
	"shopping":   "购物",
	"price":      "价格",
	"tag":        "标签 价格",
	"discount":   "折扣",
	"sale":       "促销 销售",
	"payment":    "支付",
	"transfer":   "转账",
	"exchange":   "兑换",
	"currency":   "货币",
	"bitcoin":    "比特币",
	"ethereum":   "以太坊",
	"blockchain": "区块链",
	"token":      "代币",
	"chart":      "图表",
	"graph":      "图表",
	"trend":      "趋势",
	"growth":     "增长",
	"statistic":  "统计",
	"analytics":  "分析",
	"dashboard":  "仪表盘",

	// Objects - Weather
	"sun":         "太阳",
	"moon":        "月亮",
	"rain":        "雨",
	"snow":        "雪",
	"wind":        "风",
	"weather":     "天气",
	"temperature": "温度",
	"thermometer": "温度计",
	"lightning":   "闪电",
	"storm":       "暴风雨",
	"rainbow":     "彩虹",
	"fog":         "雾",
	"ice":         "冰",
	"drop":        "水滴",
	"umbrella":    "伞",

	// Objects - Transport
	"car":        "汽车",
	"bus":        "公交车",
	"bike":       "自行车",
	"bicycle":    "自行车",
	"train":      "火车",
	"plane":      "飞机",
	"airplane":   "飞机",
	"ship":       "船",
	"boat":       "小船",
	"rocket":     "火箭",
	"helicopter": "直升机",
	"truck":      "卡车",
	"van":        "货车",
	"taxi":       "出租车",
	"scooter":    "滑板车",
	"motorcycle": "摩托车",
	"fuel":       "燃料",
	"gas":        "汽油",
	"parking":    "停车",
	"traffic":    "交通",

	// Objects - Buildings
	"building":   "建筑 大楼",
	"house":      "房子",
	"hospital":   "医院",
	"school":     "学校",
	"office":     "办公室",
	"factory":    "工厂",
	"castle":     "城堡",
	"church":     "教堂",
	"tower":      "塔",
	"bridge":     "桥",
	"lighthouse": "灯塔",
	"tent":       "帐篷",
	"warehouse":  "仓库",

	// Objects - Food & Drink
	"food":         "食物",
	"drink":        "饮料",
	"coffee":       "咖啡",
	"tea":          "茶",
	"water":        "水",
	"beer":         "啤酒",
	"wine":         "酒",
	"pizza":        "披萨",
	"burger":       "汉堡",
	"cake":         "蛋糕",
	"cookie":       "饼干",
	"bread":        "面包",
	"fruit":        "水果",
	"apple":        "苹果",
	"lemon":        "柠檬",
	"cherry":       "樱桃",
	"grape":        "葡萄",
	"strawberry":   "草莓",
	"cooking":      "烹饪",
	"kitchen":      "厨房",
	"knife":        "刀",
	"fork":         "叉",
	"spoon":        "勺子",
	"bowl":         "碗",
	"cup":          "杯子",
	"bottle":       "瓶子",
	"plate":        "盘子",
	"refrigerator": "冰箱",

	// Objects - Clothing & Fashion
	"shirt":   "衬衫",
	"tshirt":  "T恤",
	"pants":   "裤子",
	"dress":   "裙子",
	"hat":     "帽子",
	"shoe":    "鞋",
	"glasses": "眼镜",
	"watch":   "手表",
	"ring":    "戒指",
	"diamond": "钻石",
	"crown":   "皇冠",
	"gem":     "宝石",

	// Objects - Tools
	"hammer":      "锤子",
	"wrench":      "扳手",
	"screwdriver": "螺丝刀",
	"scissors":    "剪刀",
	"ruler":       "尺子",
	"pen":         "笔",
	"pencil":      "铅笔",
	"brush":       "画笔",
	"palette":     "调色板",
	"paint":       "绘制 油漆",
	"eraser":      "橡皮擦",
	"tool":        "工具",
	"gear":        "齿轮 设置",
	"settings":    "设置",
	"setting":     "设置",
	"config":      "配置",
	"slider":      "滑块",
	"switch":      "开关 切换",
	"toggle":      "切换",
	// Objects - Nature
	"tree":     "树",
	"flower":   "花",
	"leaf":     "叶子",
	"plant":    "植物",
	"grass":    "草",
	"seed":     "种子",
	"mountain": "山",
	"hill":     "小山",
	"volcano":  "火山",
	"river":    "河流",
	"lake":     "湖",
	"ocean":    "海洋",
	"sea":      "海",
	"beach":    "海滩",
	"island":   "岛屿",
	"forest":   "森林",
	"desert":   "沙漠",
	"cave":     "洞穴",
	"rock":     "岩石",
	"stone":    "石头",
	"fire":     "火",
	"earth":    "地球",
	"nature":   "自然",
	"garden":   "花园",

	// Objects - Animals
	"cat":       "猫",
	"dog":       "狗",
	"bird":      "鸟",
	"fish":      "鱼",
	"horse":     "马",
	"rabbit":    "兔子",
	"bear":      "熊",
	"lion":      "狮子",
	"tiger":     "老虎",
	"elephant":  "大象",
	"whale":     "鲸鱼",
	"dolphin":   "海豚",
	"butterfly": "蝴蝶",
	"bee":       "蜜蜂",
	"bug":       "虫子 缺陷",
	"spider":    "蜘蛛",
	"snake":     "蛇",
	"frog":      "青蛙",
	"turtle":    "乌龟",
	"penguin":   "企鹅",
	"fox":       "狐狸",
	"wolf":      "狼",
	"deer":      "鹿",
	"monkey":    "猴子",
	"panda":     "熊猫",
	"eagle":     "鹰",
	"owl":       "猫头鹰",
	"shark":     "鲨鱼",
	"octopus":   "章鱼",
	"crab":      "螃蟹",
	"paw":       "爪子",

	// Objects - Sports
	"football":   "足球",
	"basketball": "篮球",
	"tennis":     "网球",
	"baseball":   "棒球",
	"soccer":     "足球",
	"golf":       "高尔夫",
	"swimming":   "游泳",
	"running":    "跑步",
	"cycling":    "骑行",
	"skiing":     "滑雪",
	"boxing":     "拳击",
	"medal":      "奖牌",
	"trophy":     "奖杯",
	"ball":       "球",
	"dumbbell":   "哑铃",
	"fitness":    "健身",
	"yoga":       "瑜伽",
	"dance":      "舞蹈",
	"game":       "游戏",
	"puzzle":     "拼图",
	"dice":       "骰子",
	"chess":      "象棋",
	"bow":        "弓",
	"sword":      "剑",

	// Objects - Music
	"guitar":  "吉他",
	"piano":   "钢琴",
	"drum":    "鼓",
	"violin":  "小提琴",
	"trumpet": "小号",
	"melody":  "旋律",
	"song":    "歌曲",
	"tune":    "曲调",
	"podcast": "播客",
	"disc":    "唱片",
	"record":  "录制 记录",

	// Objects - Medical
	"medical":     "医疗",
	"health":      "健康",
	"medicine":    "药物",
	"pill":        "药丸",
	"syringe":     "注射器",
	"stethoscope": "听诊器",
	"heartbeat":   "心跳",
	"pulse":       "脉搏",
	"ambulance":   "救护车",
	"blood":       "血液",
	"dna":         "DNA",
	"atom":        "原子",

	// Objects - Science
	"microscope": "显微镜",
	"telescope":  "望远镜",
	"satellite":  "卫星",
	"spaceship":  "宇宙飞船",
	"astronaut":  "宇航员",
	"planet":     "行星",
	"galaxy":     "银河",
	"universe":   "宇宙",
	"meteor":     "流星",
	"experiment": "实验",
	"flask":      "烧瓶",
	"molecule":   "分子",
	"formula":    "公式",
	"lab":        "实验室",
	"science":    "科学",

	// Emotions & Expressions
	"smile":      "微笑",
	"happy":      "开心",
	"sad":        "悲伤",
	"angry":      "生气",
	"laugh":      "笑",
	"cry":        "哭",
	"love":       "爱",
	"heart":      "心 喜欢 收藏",
	"star":       "星 收藏 评分",
	"bookmark":   "书签",
	"favorite":   "收藏",
	"like":       "点赞 喜欢",
	"thumb":      "拇指",
	"hand":       "手",
	"face":       "脸 面部",
	"emoji":      "表情",
	"sticker":    "贴纸",
	"expression": "表情",
	"emotion":    "情绪",
	"surprise":   "惊讶",
	"fear":       "恐惧",
	"wink":       "眨眼",
	"grin":       "咧嘴笑",
	"frown":      "皱眉",
	"blush":      "脸红",

	// Shapes
	"circle":    "圆 圆形",
	"square":    "方 方形",
	"triangle":  "三角形",
	"rectangle": "矩形",
	"hexagon":   "六边形",
	"pentagon":  "五边形",
	"octagon":   "八边形",
	"shape":     "形状",
	"dot":       "点",
	"line":      "线条",
	"dash":      "虚线",
	"curve":     "曲线",
	"wave":      "波浪",
	"spiral":    "螺旋",
	"arc":       "弧",

	// Layout & UI
	"grid":       "网格",
	"list":       "列表",
	"table":      "表格",
	"card":       "卡片",
	"sidebar":    "侧边栏",
	"panel":      "面板",
	"tab":        "标签页",
	"dialog":     "对话框",
	"modal":      "弹窗",
	"drawer":     "抽屉",
	"tooltip":    "提示框",
	"badge":      "徽章",
	"divider":    "分割线",
	"separator":  "分隔符",
	"spinner":    "加载动画",
	"progress":   "进度",
	"breadcrumb": "面包屑",
	"pagination": "分页",
	"dropdown":   "下拉菜单",
	"accordion":  "手风琴",
	"carousel":   "轮播",
	"stepper":    "步骤条",
	"layout":     "布局",
	"widget":     "小组件",
	"component":  "组件",
	"section":    "区块",
	"container":  "容器",
	"wrapper":    "包装器",
	"frame":      "框架",

	// Status
	"success":   "成功 完成",
	"error":     "错误 失败",
	"warning":   "警告 警示",
	"info":      "信息 提示",
	"loading":   "加载中",
	"empty":     "空",
	"active":    "激活",
	"inactive":  "未激活",
	"enabled":   "启用",
	"disabled":  "禁用",
	"online":    "在线",
	"offline":   "离线",
	"busy":      "忙碌",
	"available": "可用",
	"pending":   "待处理",
	"approved":  "已批准",
	"rejected":  "已拒绝",
	"completed": "已完成",
	"cancelled": "已取消",
	"expired":   "已过期",

	// Size & Position
	"small":      "小",
	"medium":     "中",
	"large":      "大",
	"tiny":       "微小",
	"huge":       "巨大",
	"wide":       "宽",
	"narrow":     "窄",
	"tall":       "高",
	"short":      "矮 短",
	"thick":      "粗",
	"thin":       "细",
	"top":        "顶部",
	"bottom":     "底部",
	"middle":     "中间",
	"center":     "居中",
	"side":       "侧面",
	"front":      "前面",
	"corner":     "角落",
	"edge":       "边缘",
	"border":     "边框",
	"outline":    "轮廓",
	"shadow":     "阴影",
	"glow":       "发光",
	"blur":       "模糊",
	"opacity":    "透明度",
	"background": "背景",
	"foreground": "前景",
	"overlap":    "重叠",
	"behind":     "后面",
	"above":      "上方",
	"below":      "下方",

	// Colors (commonly in icon names)
	"color":  "颜色",
	"red":    "红色",
	"blue":   "蓝色",
	"green":  "绿色",
	"yellow": "黄色",
	"orange": "橙色",
	"purple": "紫色",
	"pink":   "粉色",
	"black":  "黑色",
	"white":  "白色",
	"gray":   "灰色",
	"grey":   "灰色",
	"dark":   "深色",
	"light":  "浅色 灯光",

	// Misc common words
	"flag":         "旗帜 标记",
	"award":        "奖项",
	"gift":         "礼物",
	"present":      "礼物",
	"package":      "包裹 包",
	"box":          "盒子 箱子",
	"crate":        "板条箱",
	"expand":       "展开",
	"collapse":     "折叠",
	"maximize":     "最大化",
	"minimize":     "最小化",
	"resize":       "调整大小",
	"move":         "移动",
	"drag":         "拖拽",
	"zoom":         "缩放",
	"magnify":      "放大",
	"crop":         "裁剪",
	"rotate":       "旋转",
	"flip":         "翻转",
	"align":        "对齐",
	"distribute":   "分布",
	"justify":      "两端对齐",
	"space":        "间距 太空",
	"layer":        "图层",
	"effect":       "效果",
	"animation":    "动画",
	"transition":   "过渡 转场",
	"lens":         "镜头",
	"focus":        "聚焦",
	"aperture":     "光圈",
	"flash":        "闪光",
	"portrait":     "肖像",
	"landscape":    "风景",
	"gallery":      "画廊",
	"draw":         "绘画",
	"sketch":       "素描",
	"design":       "设计",
	"creative":     "创意",
	"art":          "艺术",
	"illustration": "插图",

	// Numbers
	"0": "零",
	"1": "一",
	"2": "二",
	"3": "三",
	"4": "四",
	"5": "五",
	"6": "六",
	"7": "七",
	"8": "八",
	"9": "九",

	// Common icon name parts that aren't covered above
	"accessibility": "无障碍",
	"wheelchair":    "轮椅",
	"universal":     "通用",
	"energy":        "能量",
	"solar":         "太阳",
	"charging":      "充电",
	"outlet":        "插座",
	"adapter":       "适配器",
	"convert":       "转换",
	"transform":     "变换",
	"mirror":        "镜像",
	"clone":         "克隆",
	"duplicate":     "副本",
	"template":      "模板",
	"preset":        "预设",
	"default":       "默认",
	"custom":        "自定义",
	"personal":      "个人",
	"global":        "全局",
	"local":         "本地",
	"remote":        "远程",
	"external":      "外部",
	"internal":      "内部",
	"public":        "公开",
	"private":       "私有",
	"shared":        "共享",
	"important":     "重要",
	"urgent":        "紧急",
	"priority":      "优先级",
	"required":      "必填",
	"optional":      "可选",
	"recommended":   "推荐",
	"suggested":     "建议",
	"popular":       "流行",
	"trending":      "热门",
	"featured":      "精选",
	"latest":        "最新",
	"recent":        "最近",
	"related":       "相关",
	"similar":       "相似",
	"alternative":   "替代",
	"other":         "其他",
	"misc":          "杂项",
	"extra":         "额外",
	"bonus":         "奖励",
	"premium":       "高级",
	"free":          "免费",
	"pro":           "专业",
	"lite":          "轻量",
	"mini":          "迷你",
	"micro":         "微型",
	"mega":          "大型",
	"super":         "超级",
	"ultra":         "超",
	"max":           "最大",
	"min":           "最小",
	"smart":         "智能",
	"auto":          "自动",
	"manual":        "手动",
	"quick":         "快速",
	"fast":          "快",
	"slow":          "慢",
	"easy":          "简单",
	"simple":        "简单",
	"complex":       "复杂",
	"basic":         "基本",
	"advanced":      "高级",
	"expert":        "专家",
	"professional":  "专业",
	"debug":         "调试",
	"test":          "测试",
	"deploy":        "部署",
	"build":         "构建",
	"compile":       "编译",
	"install":       "安装",
	"launch":        "启动",
	"wizard":        "向导",
	"guide":         "指南",
	"tutorial":      "教程",
	"help":          "帮助",
	"support":       "支持",
	"about":         "关于",
	"version":       "版本",
	"license":       "许可证",
	"copyright":     "版权",
	"trademark":     "商标",
	"patent":        "专利",
	"legal":         "法律",
	"terms":         "条款",
	"agreement":     "协议",
	"contract":      "合同",
	"policy":        "策略 政策",
	"rule":          "规则",
	"condition":     "条件",
	"option":        "选项",
	"preference":    "偏好",
	"feature":       "功能",
	"function":      "函数",
	"method":        "方法",
	"property":      "属性",
	"attribute":     "属性",
	"parameter":     "参数",
	"argument":      "参数",
	"value":         "值",
	"type":          "类型",
	"class":         "类",
	"object":        "对象",
	"array":         "数组",
	"string":        "字符串",
	"number":        "数字",
	"boolean":       "布尔",
	"integer":       "整数",
	"float":         "浮点数",
	"loop":          "循环",
	"event":         "事件",
	"handler":       "处理器",
	"callback":      "回调",
	"promise":       "承诺",
	"async":         "异步",
	"thread":        "线程",
	"process":       "进程",
	"task":          "任务",
	"job":           "作业",
	"queue":         "队列",
	"stack":         "栈",
	"heap":          "堆",
	"node":          "节点",
	"hash":          "哈希",
	"reduce":        "归约",
	"format":        "格式化",
	"parse":         "解析",
	"validate":      "验证",
	"sanitize":      "清理",
	"escape":        "转义",
	"encode":        "编码",
	"decode":        "解码",
	"encrypt":       "加密",
	"decrypt":       "解密",
	"compress":      "压缩",
	"decompress":    "解压",
	"extract":       "提取",
	"bundle":        "打包",
	"minify":        "压缩",
	"optimize":      "优化",
	"lazy":          "懒加载",
	"cache":         "缓存",
	"storage":       "存储",
	"memory":        "内存",
	"disk":          "磁盘",
	"bandwidth":     "带宽",
	"latency":       "延迟",
	"timeout":       "超时",
	"retry":         "重试",
	"fallback":      "回退",
	"exception":     "异常",
	"notice":        "通知",
	"trace":         "追踪",
	"perf":          "性能",
	"benchmark":     "基准测试",
	"metric":        "指标",
	"counter":       "计数器",
	"gauge":         "仪表",
	"duration":      "持续时间",
	"frequency":     "频率",
	"rate":          "速率",
	"ratio":         "比率",
	"percent":       "百分比",
	"average":       "平均",
	"total":         "总计",
	"sum":           "合计",
	"count":         "计数",
	"range":         "范围",
	"limit":         "限制",
	"threshold":     "阈值",
	"capacity":      "容量",
	"size":          "大小",
	"weight":        "权重 重量",
	"height":        "高度",
	"width":         "宽度",
	"depth":         "深度",
	"length":        "长度",
	"area":          "面积",
	"volume":        "体积 音量",
	"density":       "密度",
	"pressure":      "压力",
	"speed":         "速度",
	"acceleration":  "加速度",
}

// iconKeywordCache caches translated keywords per icon name for performance
var (
	keywordCache   = make(map[string]string)
	keywordCacheMu sync.RWMutex
)

// translateIconName translates an English icon name to Chinese keywords.
// It splits the name by hyphens/spaces, looks up each part in the dictionary,
// and returns space-separated unique Chinese translations.
func translateIconName(name string) string {
	keywordCacheMu.RLock()
	if cached, ok := keywordCache[name]; ok {
		keywordCacheMu.RUnlock()
		return cached
	}
	keywordCacheMu.RUnlock()

	// Split by hyphens, spaces, underscores
	parts := strings.FieldsFunc(name, func(r rune) bool {
		return r == '-' || r == '_' || r == ' '
	})

	seen := make(map[string]bool)
	var zhWords []string
	for _, p := range parts {
		if zh, ok := enToZh[strings.ToLower(p)]; ok {
			// Each translation may have multiple words (space-separated)
			for _, w := range strings.Fields(zh) {
				if !seen[w] {
					seen[w] = true
					zhWords = append(zhWords, w)
				}
			}
		}
	}

	result := strings.Join(zhWords, ", ")

	keywordCacheMu.Lock()
	keywordCache[name] = result
	keywordCacheMu.Unlock()

	return result
}
