// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DialogService handles native file dialogs
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * SaveIconDialog opens a system save dialog and saves the icon to the chosen path.
 * Returns the saved file path, or empty string if cancelled.
 * @param {string} id
 * @param {string} format
 * @param {number} size
 * @param {string} color
 * @returns {$CancellablePromise<string>}
 */
export function SaveIconDialog(id, format, size, color) {
    return $Call.ByID(2384386973, id, format, size, color);
}
