// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * IconService manages the icon library with SQLite backend
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Close closes the database
 * @returns {$CancellablePromise<void>}
 */
export function Close() {
    return $Call.ByID(4033758392);
}

/**
 * ExportIcon exports an icon with the given options, returns the file path
 * @param {string} id
 * @param {$models.ExportOptions} options
 * @returns {$CancellablePromise<string>}
 */
export function ExportIcon(id, options) {
    return $Call.ByID(2008942751, id, options);
}

/**
 * GetCategories returns all categories with icon counts
 * @returns {$CancellablePromise<$models.CategoryInfo[]>}
 */
export function GetCategories() {
    return $Call.ByID(995442604).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetCategoriesByPackage returns categories (subfolders) for a given package
 * @param {string} pkg
 * @returns {$CancellablePromise<$models.CategoryInfo[]>}
 */
export function GetCategoriesByPackage(pkg) {
    return $Call.ByID(3372982663, pkg).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetIcon retrieves a single icon by ID
 * @param {string} id
 * @returns {$CancellablePromise<$models.Icon>}
 */
export function GetIcon(id) {
    return $Call.ByID(361324289, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetIconSVG returns the SVG content of an icon
 * @param {string} id
 * @returns {$CancellablePromise<string>}
 */
export function GetIconSVG(id) {
    return $Call.ByID(3757637253, id);
}

/**
 * GetPackages returns all packages with icon counts
 * @returns {$CancellablePromise<$models.CategoryInfo[]>}
 */
export function GetPackages() {
    return $Call.ByID(3273991673).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetStats returns icon library statistics
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetStats() {
    return $Call.ByID(2801795251).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * Search searches icons by keyword using FTS5
 * @param {string} query
 * @param {string} pkg
 * @param {string} category
 * @param {number} page
 * @param {number} pageSize
 * @returns {$CancellablePromise<$models.SearchResult>}
 */
export function Search(query, pkg, category, page, pageSize) {
    return $Call.ByID(181161080, query, pkg, category, page, pageSize).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.CategoryInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.Icon.createFrom;
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = $models.SearchResult.createFrom;
