// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CategoryInfo represents a category with icon count
 */
export class CategoryInfo {
    /**
     * Creates a new CategoryInfo instance.
     * @param {Partial<CategoryInfo>} [$$source = {}] - The source object to create the CategoryInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CategoryInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CategoryInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CategoryInfo(/** @type {Partial<CategoryInfo>} */($$parsedSource));
    }
}

/**
 * ExportOptions for downloading icons
 */
export class ExportOptions {
    /**
     * Creates a new ExportOptions instance.
     * @param {Partial<ExportOptions>} [$$source = {}] - The source object to create the ExportOptions.
     */
    constructor($$source = {}) {
        if (!("format" in $$source)) {
            /**
             * "svg" or "png"
             * @member
             * @type {string}
             */
            this["format"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * pixel size for PNG
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("color" in $$source)) {
            /**
             * hex color, e.g. "#FF5722"
             * @member
             * @type {string}
             */
            this["color"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ExportOptions}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExportOptions(/** @type {Partial<ExportOptions>} */($$parsedSource));
    }
}

/**
 * Icon represents a single SVG icon in the library
 */
export class Icon {
    /**
     * Creates a new Icon instance.
     * @param {Partial<Icon>} [$$source = {}] - The source object to create the Icon.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["category"] = "";
        }
        if (!("package" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["package"] = "";
        }
        if (!("tags" in $$source)) {
            /**
             * comma-separated, stored in DB
             * @member
             * @type {string}
             */
            this["tags"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * relative path from icons root
             * @member
             * @type {string}
             */
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Icon instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Icon}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Icon(/** @type {Partial<Icon>} */($$parsedSource));
    }
}

/**
 * SearchResult represents paginated search results
 */
export class SearchResult {
    /**
     * Creates a new SearchResult instance.
     * @param {Partial<SearchResult>} [$$source = {}] - The source object to create the SearchResult.
     */
    constructor($$source = {}) {
        if (!("icons" in $$source)) {
            /**
             * @member
             * @type {Icon[]}
             */
            this["icons"] = [];
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("page" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pageSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SearchResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("icons" in $$parsedSource) {
            $$parsedSource["icons"] = $$createField0_0($$parsedSource["icons"]);
        }
        return new SearchResult(/** @type {Partial<SearchResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Icon.createFrom;
const $$createType1 = $Create.Array($$createType0);
